CREATE DATABASE SWIFTLOGISTICS

USE SWIFTLOGISTICS

-- Employee_Details Table 

CREATE TABLE Employee_Details
(Emp_ID INT NOT NULL PRIMARY KEY, Emp_NAME VARCHAR(30) NOT NULL, Emp_BRANCH VARCHAR(15) NOT NULL, 
Emp_DESIGNATION VARCHAR(40) NOT NULL, Emp_ADDR VARCHAR(100) NOT NULL, Emp_CONT_NO VARCHAR(10) NOT NULL)

SELECT * FROM Employee_Details

-- Membership Table

CREATE TABLE Membership
(M_ID INT NOT NULL PRIMARY KEY, START_DATE DATETIME, END_DATE DATETIME)

SELECT * FROM Membership

--Customer Table

CREATE TABLE Customer
(Cust_ID INT NOT NULL PRIMARY KEY, Cust_NAME VARCHAR(30) NOT NULL, Cust_EMAIL_ID VARCHAR(50), 
Cust_CONT_NO VARCHAR(10) NOT NULL, Cust_ADDR VARCHAR(100) NOT NULL, Cust_TYPE VARCHAR(30), 
Membership_M_ID INT NOT NULL FOREIGN KEY REFERENCES Membership(M_ID))

SELECT * FROM Customer

-- Shipment_Details Table

CREATE TABLE Shipment_Details
(SD_ID VARCHAR(10) NOT NULL PRIMARY KEY, SD_CONTENT VARCHAR(40) NOT NULL, SD_DOMAIN VARCHAR(15) NOT NULL,
SD_TYPE VARCHAR(15) NOT NULL, SD_WEIGHT VARCHAR(15), SD_CHARGES INT, SD_ADDR VARCHAR(100) NOT NULL, 
DS_ADDR VARCHAR(100) NOT NULL, Customer_Cust_ID INT FOREIGN KEY REFERENCES Customer(Cust_ID))

SELECT * FROM Shipment_Details

--Payment_Details Table

CREATE TABLE Payment_Details
(PAYMENT_ID VARCHAR(10) PRIMARY KEY NOT NULL, AMOUNT INT NOT NULL, PAYMENT_STATUS VARCHAR(10) NOT NULL,
PAYMENT_DATE DATETIME NOT NULL, PAYMENT_MODE VARCHAR(25) NOT NULL, 
Shipment_SH_ID VARCHAR(10) FOREIGN KEY REFERENCES Shipment_Details(SD_ID),
Shipment_Client_C_ID INT FOREIGN KEY REFERENCES Customer(Cust_ID))

SELECT * FROM Payment_Details

-- Status Table

CREATE TABLE Status
(CURRENT_ST VARCHAR(15) NOT NULL, SENT_DATE DATETIME, DELIVERY_DATE DATETIME, 
SH_ID VARCHAR(10) PRIMARY KEY NOT NULL)

SELECT * FROM Status

--Employee Manages Shipment Table

CREATE TABLE Employee_Manages_Shipment
(Employee_E_ID INT FOREIGN KEY REFERENCES Employee_Details(Emp_ID), 
Shipment_SH_ID VARCHAR(10) FOREIGN KEY REFERENCES Shipment_Details(SD_ID),
Status_SH_ID VARCHAR(10) FOREIGN KEY REFERENCES Status(SH_ID))

SELECT * FROM Employee_Manages_Shipment